require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RrcsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Rrc. As you add validations to Rrc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RrcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rrcs as @rrcs" do
      rrc = Rrc.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rrcs)).to eq([rrc])
    end
  end

  describe "GET #show" do
    it "assigns the requested rrc as @rrc" do
      rrc = Rrc.create! valid_attributes
      get :show, {:id => rrc.to_param}, valid_session
      expect(assigns(:rrc)).to eq(rrc)
    end
  end

  describe "GET #new" do
    it "assigns a new rrc as @rrc" do
      get :new, {}, valid_session
      expect(assigns(:rrc)).to be_a_new(Rrc)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rrc as @rrc" do
      rrc = Rrc.create! valid_attributes
      get :edit, {:id => rrc.to_param}, valid_session
      expect(assigns(:rrc)).to eq(rrc)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Rrc" do
        expect {
          post :create, {:rrc => valid_attributes}, valid_session
        }.to change(Rrc, :count).by(1)
      end

      it "assigns a newly created rrc as @rrc" do
        post :create, {:rrc => valid_attributes}, valid_session
        expect(assigns(:rrc)).to be_a(Rrc)
        expect(assigns(:rrc)).to be_persisted
      end

      it "redirects to the created rrc" do
        post :create, {:rrc => valid_attributes}, valid_session
        expect(response).to redirect_to(Rrc.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rrc as @rrc" do
        post :create, {:rrc => invalid_attributes}, valid_session
        expect(assigns(:rrc)).to be_a_new(Rrc)
      end

      it "re-renders the 'new' template" do
        post :create, {:rrc => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rrc" do
        rrc = Rrc.create! valid_attributes
        put :update, {:id => rrc.to_param, :rrc => new_attributes}, valid_session
        rrc.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rrc as @rrc" do
        rrc = Rrc.create! valid_attributes
        put :update, {:id => rrc.to_param, :rrc => valid_attributes}, valid_session
        expect(assigns(:rrc)).to eq(rrc)
      end

      it "redirects to the rrc" do
        rrc = Rrc.create! valid_attributes
        put :update, {:id => rrc.to_param, :rrc => valid_attributes}, valid_session
        expect(response).to redirect_to(rrc)
      end
    end

    context "with invalid params" do
      it "assigns the rrc as @rrc" do
        rrc = Rrc.create! valid_attributes
        put :update, {:id => rrc.to_param, :rrc => invalid_attributes}, valid_session
        expect(assigns(:rrc)).to eq(rrc)
      end

      it "re-renders the 'edit' template" do
        rrc = Rrc.create! valid_attributes
        put :update, {:id => rrc.to_param, :rrc => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rrc" do
      rrc = Rrc.create! valid_attributes
      expect {
        delete :destroy, {:id => rrc.to_param}, valid_session
      }.to change(Rrc, :count).by(-1)
    end

    it "redirects to the rrcs list" do
      rrc = Rrc.create! valid_attributes
      delete :destroy, {:id => rrc.to_param}, valid_session
      expect(response).to redirect_to(rrcs_url)
    end
  end

end
