require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ImlsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Iml. As you add validations to Iml, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all imls as @imls" do
      iml = Iml.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:imls)).to eq([iml])
    end
  end

  describe "GET #show" do
    it "assigns the requested iml as @iml" do
      iml = Iml.create! valid_attributes
      get :show, {:id => iml.to_param}, valid_session
      expect(assigns(:iml)).to eq(iml)
    end
  end

  describe "GET #new" do
    it "assigns a new iml as @iml" do
      get :new, {}, valid_session
      expect(assigns(:iml)).to be_a_new(Iml)
    end
  end

  describe "GET #edit" do
    it "assigns the requested iml as @iml" do
      iml = Iml.create! valid_attributes
      get :edit, {:id => iml.to_param}, valid_session
      expect(assigns(:iml)).to eq(iml)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Iml" do
        expect {
          post :create, {:iml => valid_attributes}, valid_session
        }.to change(Iml, :count).by(1)
      end

      it "assigns a newly created iml as @iml" do
        post :create, {:iml => valid_attributes}, valid_session
        expect(assigns(:iml)).to be_a(Iml)
        expect(assigns(:iml)).to be_persisted
      end

      it "redirects to the created iml" do
        post :create, {:iml => valid_attributes}, valid_session
        expect(response).to redirect_to(Iml.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved iml as @iml" do
        post :create, {:iml => invalid_attributes}, valid_session
        expect(assigns(:iml)).to be_a_new(Iml)
      end

      it "re-renders the 'new' template" do
        post :create, {:iml => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested iml" do
        iml = Iml.create! valid_attributes
        put :update, {:id => iml.to_param, :iml => new_attributes}, valid_session
        iml.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested iml as @iml" do
        iml = Iml.create! valid_attributes
        put :update, {:id => iml.to_param, :iml => valid_attributes}, valid_session
        expect(assigns(:iml)).to eq(iml)
      end

      it "redirects to the iml" do
        iml = Iml.create! valid_attributes
        put :update, {:id => iml.to_param, :iml => valid_attributes}, valid_session
        expect(response).to redirect_to(iml)
      end
    end

    context "with invalid params" do
      it "assigns the iml as @iml" do
        iml = Iml.create! valid_attributes
        put :update, {:id => iml.to_param, :iml => invalid_attributes}, valid_session
        expect(assigns(:iml)).to eq(iml)
      end

      it "re-renders the 'edit' template" do
        iml = Iml.create! valid_attributes
        put :update, {:id => iml.to_param, :iml => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested iml" do
      iml = Iml.create! valid_attributes
      expect {
        delete :destroy, {:id => iml.to_param}, valid_session
      }.to change(Iml, :count).by(-1)
    end

    it "redirects to the imls list" do
      iml = Iml.create! valid_attributes
      delete :destroy, {:id => iml.to_param}, valid_session
      expect(response).to redirect_to(imls_url)
    end
  end

end
