require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IordersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Iorder. As you add validations to Iorder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IordersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all iorders as @iorders" do
      iorder = Iorder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:iorders)).to eq([iorder])
    end
  end

  describe "GET #show" do
    it "assigns the requested iorder as @iorder" do
      iorder = Iorder.create! valid_attributes
      get :show, {:id => iorder.to_param}, valid_session
      expect(assigns(:iorder)).to eq(iorder)
    end
  end

  describe "GET #new" do
    it "assigns a new iorder as @iorder" do
      get :new, {}, valid_session
      expect(assigns(:iorder)).to be_a_new(Iorder)
    end
  end

  describe "GET #edit" do
    it "assigns the requested iorder as @iorder" do
      iorder = Iorder.create! valid_attributes
      get :edit, {:id => iorder.to_param}, valid_session
      expect(assigns(:iorder)).to eq(iorder)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Iorder" do
        expect {
          post :create, {:iorder => valid_attributes}, valid_session
        }.to change(Iorder, :count).by(1)
      end

      it "assigns a newly created iorder as @iorder" do
        post :create, {:iorder => valid_attributes}, valid_session
        expect(assigns(:iorder)).to be_a(Iorder)
        expect(assigns(:iorder)).to be_persisted
      end

      it "redirects to the created iorder" do
        post :create, {:iorder => valid_attributes}, valid_session
        expect(response).to redirect_to(Iorder.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved iorder as @iorder" do
        post :create, {:iorder => invalid_attributes}, valid_session
        expect(assigns(:iorder)).to be_a_new(Iorder)
      end

      it "re-renders the 'new' template" do
        post :create, {:iorder => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested iorder" do
        iorder = Iorder.create! valid_attributes
        put :update, {:id => iorder.to_param, :iorder => new_attributes}, valid_session
        iorder.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested iorder as @iorder" do
        iorder = Iorder.create! valid_attributes
        put :update, {:id => iorder.to_param, :iorder => valid_attributes}, valid_session
        expect(assigns(:iorder)).to eq(iorder)
      end

      it "redirects to the iorder" do
        iorder = Iorder.create! valid_attributes
        put :update, {:id => iorder.to_param, :iorder => valid_attributes}, valid_session
        expect(response).to redirect_to(iorder)
      end
    end

    context "with invalid params" do
      it "assigns the iorder as @iorder" do
        iorder = Iorder.create! valid_attributes
        put :update, {:id => iorder.to_param, :iorder => invalid_attributes}, valid_session
        expect(assigns(:iorder)).to eq(iorder)
      end

      it "re-renders the 'edit' template" do
        iorder = Iorder.create! valid_attributes
        put :update, {:id => iorder.to_param, :iorder => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested iorder" do
      iorder = Iorder.create! valid_attributes
      expect {
        delete :destroy, {:id => iorder.to_param}, valid_session
      }.to change(Iorder, :count).by(-1)
    end

    it "redirects to the iorders list" do
      iorder = Iorder.create! valid_attributes
      delete :destroy, {:id => iorder.to_param}, valid_session
      expect(response).to redirect_to(iorders_url)
    end
  end

end
