require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TreolansController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Treolan. As you add validations to Treolan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TreolansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all treolans as @treolans" do
      treolan = Treolan.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:treolans)).to eq([treolan])
    end
  end

  describe "GET #show" do
    it "assigns the requested treolan as @treolan" do
      treolan = Treolan.create! valid_attributes
      get :show, {:id => treolan.to_param}, valid_session
      expect(assigns(:treolan)).to eq(treolan)
    end
  end

  describe "GET #new" do
    it "assigns a new treolan as @treolan" do
      get :new, {}, valid_session
      expect(assigns(:treolan)).to be_a_new(Treolan)
    end
  end

  describe "GET #edit" do
    it "assigns the requested treolan as @treolan" do
      treolan = Treolan.create! valid_attributes
      get :edit, {:id => treolan.to_param}, valid_session
      expect(assigns(:treolan)).to eq(treolan)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Treolan" do
        expect {
          post :create, {:treolan => valid_attributes}, valid_session
        }.to change(Treolan, :count).by(1)
      end

      it "assigns a newly created treolan as @treolan" do
        post :create, {:treolan => valid_attributes}, valid_session
        expect(assigns(:treolan)).to be_a(Treolan)
        expect(assigns(:treolan)).to be_persisted
      end

      it "redirects to the created treolan" do
        post :create, {:treolan => valid_attributes}, valid_session
        expect(response).to redirect_to(Treolan.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved treolan as @treolan" do
        post :create, {:treolan => invalid_attributes}, valid_session
        expect(assigns(:treolan)).to be_a_new(Treolan)
      end

      it "re-renders the 'new' template" do
        post :create, {:treolan => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested treolan" do
        treolan = Treolan.create! valid_attributes
        put :update, {:id => treolan.to_param, :treolan => new_attributes}, valid_session
        treolan.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested treolan as @treolan" do
        treolan = Treolan.create! valid_attributes
        put :update, {:id => treolan.to_param, :treolan => valid_attributes}, valid_session
        expect(assigns(:treolan)).to eq(treolan)
      end

      it "redirects to the treolan" do
        treolan = Treolan.create! valid_attributes
        put :update, {:id => treolan.to_param, :treolan => valid_attributes}, valid_session
        expect(response).to redirect_to(treolan)
      end
    end

    context "with invalid params" do
      it "assigns the treolan as @treolan" do
        treolan = Treolan.create! valid_attributes
        put :update, {:id => treolan.to_param, :treolan => invalid_attributes}, valid_session
        expect(assigns(:treolan)).to eq(treolan)
      end

      it "re-renders the 'edit' template" do
        treolan = Treolan.create! valid_attributes
        put :update, {:id => treolan.to_param, :treolan => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested treolan" do
      treolan = Treolan.create! valid_attributes
      expect {
        delete :destroy, {:id => treolan.to_param}, valid_session
      }.to change(Treolan, :count).by(-1)
    end

    it "redirects to the treolans list" do
      treolan = Treolan.create! valid_attributes
      delete :destroy, {:id => treolan.to_param}, valid_session
      expect(response).to redirect_to(treolans_url)
    end
  end

end
